{% set name = "django-sequences" %}
{% set version = "2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f697b13951cf99eff6bb2eaad40503aaad0ad8f161f53eb10344a80a3df2515d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.2
    - poetry
  run:
    - django >=3.2
    - python >=3.6.2

test:
  imports:
    - sequences
    - sequences.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aaugustin/django-sequences
  summary: Generate gapless sequences of integer values.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
