{% set name = "django-sequences" %}
{% set version = "2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-sequences-{{ version }}.tar.gz
  sha256: cb5409feff30c7a35542e4a89eb438c58b91a457ad95c126e8c6e5edf01f6287

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.2
    - poetry
  run:
    - django >=3.2
    - python >=3.6.2

test:
  imports:
    - sequences
    - sequences.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aaugustin/django-sequences
  summary: Generate gapless sequences of integer values.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
